# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('school', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('tms', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '七年级'), (8, '八年级'), (9, '九年级'), (10, '高一'), (11, '高二'), (12, '高三')])),
                ('classes', models.IntegerField()),
                ('school', models.IntegerField(blank=True, null=True)),
                ('subjectCd', models.IntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语'), (4, '物理'), (5, '化学'), (6, '生物'), (7, '政治'), (8, '地理'), (9, '历史')])),
                ('textbook', models.IntegerField()),
                ('tms', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringCore.Teacher')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teacher_classes',
            unique_together=set([('teacher', 'grade', 'classes')]),
        ),
    ]
