# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerate',
            name='submitNum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
