# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectCd', models.IntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语'), (4, '物理'), (5, '化学'), (6, '生物'), (7, '政治'), (8, '地理'), (9, '历史')])),
                ('chapter', models.IntegerField()),
                ('chapterName', models.CharField(max_length=60)),
                ('tms', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
