# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoringCore', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField()),
                ('topicType', models.IntegerField(choices=[(1, '选择题'), (2, '填空题'), (3, '问答题'), (4, '判断题')])),
                ('addr1', models.CharField(max_length=10)),
                ('addr2', models.CharField(max_length=10)),
                ('addr3', models.CharField(blank=True, max_length=10)),
                ('addr4', models.CharField(blank=True, max_length=10)),
                ('question', models.CharField(blank=True, max_length=400)),
                ('answer', models.CharField(max_length=400)),
                ('point', models.IntegerField()),
                ('option', models.CharField(blank=True, max_length=10)),
                ('tms', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringCore.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbookName', models.CharField(blank=True, max_length=60)),
                ('publisher', models.CharField(blank=True, max_length=30)),
                ('grade', models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '七年级'), (8, '八年级'), (9, '九年级'), (10, '高一'), (11, '高二'), (12, '高三')])),
                ('subjectCd', models.IntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语'), (4, '物理'), (5, '化学'), (6, '生物'), (7, '政治'), (8, '地理'), (9, '历史')])),
                ('semester', models.IntegerField(choices=[(1, '上学期'), (2, '下学期')])),
                ('tms', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher_classes',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringCore.Textbook'),
        ),
        migrations.AddField(
            model_name='card',
            name='textbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoringCore.Textbook'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='card_topic',
            unique_together=set([('card', 'topic')]),
        ),
    ]
