# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoringCore', '0003_auto_20161029_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_topic',
            name='option',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
