# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoringCore', '0004_auto_20161029_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('school', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('grade', models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '七年级'), (8, '八年级'), (9, '九年级'), (10, '高一'), (11, '高二'), (12, '高三')])),
                ('classes', models.IntegerField()),
                ('tms', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=400)),
                ('score', models.IntegerField()),
                ('grade', models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '七年级'), (8, '八年级'), (9, '九年级'), (10, '高一'), (11, '高二'), (12, '高三')])),
                ('classes', models.IntegerField()),
                ('tms', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringCore.Card')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoringCore.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('student', 'card', 'topic')]),
        ),
    ]
